apiVersion: v1
kind: Service
metadata:
  name: pastebin-service
spec:
  type: LoadBalancer
  selector:
    app: pastebin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
